"""
Operator Inference on re-projected data, on the Lall-balanced basis.

Instead of taking dz/dt from finite differences of z = Psi^T x -- which mixes in
the closure error, the sampling error of the time derivative, and the noise in
the decayed tail -- the training pairs are generated by the *projected* dynamics
themselves:

    z = Psi^T x   along the training trajectories,
    dz/dt = Psi^T f(Phi z),

with f the divergence-projected perturbation dynamics of the FOM.  This is
re-projection in the sense of Peherstorfer (2020): the data is made consistent
with the reduced model one is trying to infer, so the least-squares fit has a
zero-residual solution and OpInf recovers the intrusive Petrov-Galerkin
operators exactly.

Because the Navier-Stokes right-hand side is exactly quadratic,

    Psi^T f(Phi z) = (Psi^T A Phi) z + Psi^T H(Phi z, Phi z),

is exactly linear-plus-quadratic in z, so the fit residual should be at machine
precision.  That is checked at the end and is the main correctness test here.

What this buys diagnostically: any remaining error in the forecast is due to the
*projection* alone -- the choice of Phi and Psi and the truncation -- and not to
how the operators were estimated.  Regularization is therefore zero by default.

Usage: python train_reprojection.py [--r 20] [--reg 0.0]
Saves opinf_reproj_r<r>.npy.
"""

import argparse
import os
import time as timer

import numpy as np
import scipy.linalg as sla

from cavity import Cavity, BC
from balanced_opinf import ROM, poly_index, poly_features
from train_pod_opinf import forecast, get_pod
from train_models import load_train, HERE
from compute_preprojection import load_train_reduced, pod_basis_reduced

BC_PERT = [0, 0, 0, 0, 0, 0, 0, 0]      # perturbations vanish on all walls


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--r", type=int, default=20)
    ap.add_argument("--reg", type=float, default=0.0)
    ap.add_argument("--basis", choices=["balanced", "pod"], default="balanced")
    ap.add_argument("--pre", type=int, default=0,
                    help="use the pre-projected bases; the FOM right-hand side "
                         "is still evaluated in the full space at Phi z")
    ap.add_argument("--sweep", action="store_true",
                    help="sweep the regularization and keep the model with the "
                         "best forecast.  With re-projected data lambda = 0 has "
                         "a zero-residual solution (the exact Petrov-Galerkin "
                         "operators), so any lambda > 0 deliberately trades "
                         "exactness for a tamer nonlinear term -- which is the "
                         "term that makes the exact model diverge.")
    args = ap.parse_args()
    r = args.r

    trajs_n, betas, time = load_train()
    trajs = [abs(b)*T for b, T in zip(betas, trajs_n)]

    if args.pre:
        U = None
        if args.basis == "pod":
            from compute_preprojection import load_preproj
            U = load_preproj(args.pre)
            Phi = Psi = U[:, :r]
            Phi_r = Psi_r = pod_basis_reduced(r, args.pre)
            print(f"POD basis, r = {r}, pre-projected onto {args.pre} modes")
        else:
            d = np.load(os.path.join(HERE, f"balancing_pre{args.pre}_r50.npy"),
                        allow_pickle=True).item()
            Phi, Psi = d["Phi"][:, :r], d["Psi"][:, :r]
            Phi_r, Psi_r = d["Phi_red"][:, :r], d["Psi_red"][:, :r]
            print(f"Lall-balanced basis, r = {r}, pre-projected onto "
                  f"{args.pre} modes")
    elif args.basis == "pod":
        Phi = Psi = Phi_r = Psi_r = get_pod(trajs, r)
        print(f"POD basis, r = {r} (orthogonal: Phi = Psi)")
    else:
        d = np.load(os.path.join(HERE, "balancing_r50.npy"),
                    allow_pickle=True).item()
        Phi, Psi = d["Phi"][:, :r], d["Psi"][:, :r]
        Phi_r, Psi_r = Phi, Psi
        print(f"Lall-balanced basis, r = {r} ({d['m_ckpt']} checkpoints, "
              f"stride {d['q_ckpt']}); biorth = "
              f"{np.linalg.norm(Psi.T @ Phi - np.eye(r)):.2e}")

    cav = Cavity()
    f = lambda q: cav.fom.evaluate_fom_dynamics(q, BC, BC_PERT)

    t0 = timer.time()
    Zs, Fs = [], []
    for j, X in enumerate(trajs):
        Z = Psi.T @ X                               # latent coordinates
        Xr = Phi @ Z                                # re-projected states
        F = Psi.T @ np.column_stack([f(Xr[:, k]) for k in range(Xr.shape[1])])
        Zs.append(Z)
        Fs.append(F)
        print(f"  trajectory {j} (beta = {betas[j]:+g}): {Z.shape[1]} "
              f"re-projected evaluations", flush=True)
    print(f"re-projection took {timer.time() - t0:.1f} s "
          f"({sum(Z.shape[1] for Z in Zs)} FOM right-hand sides)")

    Z = np.concatenate(Zs, axis=1)
    F = np.concatenate(Fs, axis=1)
    idx = poly_index(r, 2)
    D = np.concatenate((Z, poly_features(Z, idx)), axis=0)
    dd = D.shape[0]
    den = sum(np.linalg.norm(X)**2 for X in trajs)
    proj = np.sqrt(sum(np.linalg.norm(X - Phi @ (Psi.T @ X))**2
                       for X in trajs)/den)

    def fit(reg):
        # No trajectory weighting: the re-projected pairs are exact, so every
        # sample is equally informative and there is no noise to balance.
        Gam = np.zeros(dd)
        Gam[r:] = np.sqrt(reg)
        O = sla.lstsq(np.concatenate((D.T, np.diag(Gam))),
                      np.concatenate((F.T, np.zeros((dd, r)))),
                      lapack_driver="gelsy")[0].T
        return O[:, :r], O[:, r:], np.linalg.norm(F - O @ D)/np.linalg.norm(F)

    grid = (10.0**np.arange(-10, 3, 1.0) if args.sweep else [args.reg])
    if args.sweep:
        print(f"\n{'lambda':>9}{'residual':>12}{'maxRe(Ar)':>12}{'||Hr||':>11}"
              f"{'err':>10}  status")
    best = None
    for reg in grid:
        Ar, Hr, res = fit(reg)
        J, err, nbad = forecast(ROM(Ar, Hr, 2), Phi, Psi, trajs, time)
        ev = np.linalg.eigvals(Ar).real.max()
        if args.sweep:
            st = "ok" if nbad == 0 else f"{nbad}/{len(trajs)} diverged"
            es = f"{err:10.4f}" if np.isfinite(err) else f"{'inf':>10}"
            print(f"{reg:>9.0e}{res:>12.2e}{ev:>+12.4f}"
                  f"{np.linalg.norm(Hr):>11.2e}{es}  {st}")
        if np.isfinite(err) and (best is None or err < best[0]):
            best = (err, reg, Ar, Hr, res, J, ev)
        # With a single explicit lambda there is nothing to select: keep the fit
        # even if it diverges.  These operators are mainly used as the SEED for
        # train_gas_opinf.py, which supplies the stability the unconstrained fit
        # lacks, so a divergent forecast is expected and not a reason to discard
        # them -- rejecting it would force the seed toward the over-regularized,
        # nearly-linear end of the sweep.
        if not args.sweep and best is None:
            best = (err, reg, Ar, Hr, res, J, ev)
    if best is None:
        print("every regularization diverged; nothing saved.")
        return
    err, reg, Ar, Hr, res, J, ev = best
    print(f"\nbest lambda = {reg:.0e}: residual {res:.3e}, "
          f"max Re eig(Ar) = {ev:+.6f}, ||Ar|| = {np.linalg.norm(Ar):.2f}, "
          f"||Hr|| = {np.linalg.norm(Hr):.2e}")
    print(f"forecast: J = {J:.4e}, rel state error = {err:.4f}   "
          f"(projection floor {proj:.4f})")
    args.reg = reg

    tag = f"_pre{args.pre}" if args.pre else ""
    out = os.path.join(HERE, f"opinf_reproj_{args.basis}{tag}_r{r}.npy")
    np.save(out, dict(Phi=Phi, Psi=Psi, Phi_red=Phi_r, Psi_red=Psi_r,
                      Ar=Ar, Hr=Hr, reg=args.reg, J=J, err=err, proj=proj,
                      residual=res, r_pre=args.pre), allow_pickle=True)
    print(f"saved -> {out}")


if __name__ == "__main__":
    main()
